### ISSUE TITLE
Need to track a few more things from los

### ISSUE THREAD

**Issue by RoninByte** [yaap/manifest#16]
https://github.com/LineageOS/android_vendor_qcom_opensource_core-utils-vendor
https://github.com/LineageOS/android_vendor_qcom_opensource_interfaces
vendor_qcom_opensource_data-ipa-cfg-mgr needs to be updated too
 and drop cryptfs_hw

all of this is needed to build for kalama platform devices

**Comment by poad42** [comment]
Make a PR.
