### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by TheWildJames** [yaap/manifest#19]
source build/envsetup.sh
lunch yaap_device-user && m yaap
including vendor/qcom/opensource/core-utils/vendorsetup.sh
including vendor/yaap/vendorsetup.sh
automatically selected latest release: ap3a
to choose a different release use the form <product>-<release>-<variant>
Trying dependencies-only mode on a non-existing device tree?
In file included from build/make/core/config.mk:378:
In file included from build/make/core/envsetup.mk:351:
build/make/core/product_config.mk:226: error: Cannot locate config makefile for product "yaap_device".
19:31:05 dumpvars failed with: exit status 1

I get this error above following steps to build. My goal is to build some of your kernels and im not sure if i am doing that right? 

Thanks James

**Comment by Orthoxodus** [comment]
Go to device/xiaomi/vayu and edit AndroidProducts.mk and lineage_vayu.mk for example

**Comment by idoybh** [comment]
Not where we teach that kind of stuff

**Comment by Orthoxodus** [comment]
Bruh lmao

На чт, 26.12.2024 г., 15:52 ч. Ido Ben-Hur ***@***.***>
написа:
